# NUMPY
NUMPY IS A LIBRARY FOR PYTHON PROGRAMMING LANGUAGE 
NUMPY SUPPORTS FOR LARGE ,MULTIDIMENSIONAL ARRAYS AND MATRICES, ALONG WITH A LARGE COLLECTION OF HIGH-LEVEL MATHEMATICAL FUNCTIONS TO OPERATE ON THESE ARRAYS.

In [ ]:
NUMPY INCLUDES SEVERAL FUNCTIONS FOR CREATING ARRAYS.YOU CAN INITILIZE ARRAYS WITH "ONES" OR "ZEROS",AND YOU CAN ALSO 
CREATE ARRAYS THAT FILLED WITH CONSTANT VALUES OR RANDOM VALUES.

In [13]:
import numpy as np
a = np.ones((3,6))
print(a)
b = np.zeros((2,4))
c = np.random.random(3)
d = np.full((2,2),12)
print(b)
print(c)
print(d)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0.23227906 0.55942264 0.36286415]
[[12 12]
 [12 12]]


In [ ]:
--THERE IS ALSO OTHER FUNCTION WHICH IS AN EMPTY FUNCTION np.empty() FOR CREATING AN ARRAY OF UNINITIALIZED ELEMENTS 
THE np.eye() and np.identity() ARE FOR CREATING IDENTITY ARRAYS FOR MATRIX CALCULATIONS 
---YOU CAN OPTIONALLY SPECIFY THE DATA TYPE FOR ARRAY ELEMENTS AT THE TIME OF CREATION.

In [16]:
d = np.full((2,2,),11)
dtype=np.floa
print(d)

SyntaxError: invalid syntax (<ipython-input-16-1eb10cc3485c>, line 2)

In [ ]:
---COPY FUNCTION copy() CREATES A COPY OF AN ARRAY FOE EXAMPLE , a=b.copy()
---THE loadtxt() function can be used to load data from a file into an array.The load array is used to load data from
a file into an array
---THE save() FUNCTION IS USED TO SAVE A NUMPY ARRAY TO A FILE

### NUMPY ARRAY SLICING
SLICING CAN BE APPLIED TO NUMPY ARRAYS AS WITH PYTHON LISTS TO EXTRACT A SUBSET OF AN ARRAY .
AN ARRAY SLICE REFERS TO THE ACTUAL ELEMENTS ,CHANGING THE VALUES IN THE SLICE CHANGES THE VALUE OF THE ARRAY
--TO SLICE AN ARRAY ,YOU INDICATE THE START:STOP:STEP OF THE SUBSET IN SQUARE BRACKETS.
FOR EXAMPLE a[1:5:2] RETURNS THE VALUE OF 1 AND 3.

---FOR A MULTIDIMENSIONAL ARRAY ,SPECIFY ELEMENTS FOR EACH DIMENSION SEPERATED BY COMMA.
FOR EXAMPLE b[0:2:1] RETURNS THE SECOND ELEMENT IN THE FIRST TWO ROWS.
-AN ECLIPSIS ... IS USED TO INDICATE SELECTION ALONG AN ENTIRE DIMENSION.
FOR EXAMPLE b[...,2] RETURNS THE THIRD ELEMENT OF EVERY ROW.

THE CODE BELOW DEMONSTRATES SEVERAL SLICING VARIATIONS:


In [17]:
import numpy as np
x = np.arange(8)
y = x[0:4]
z = x[6: ]
print(x)
print(y)
print(z)

z[1] =10
print(x)

a = np.array([[10,11,12,13,14,15,16],[20,21,22,23,24,25,26]])
print(a[0:2,1])
print(a[...,3])
print(a[ : ,3])

[0 1 2 3 4 5 6 7]
[0 1 2 3]
[6 7]
[ 0  1  2  3  4  5  6 10]
[11 21]
[13 23]
[13 23]


# NUMPY ARTHEMETIC FUNCTIONS
ARTHEMETIC NUMPY FUNCTIONS CAN BE APPLIED TO TWO NUMPY ARRAYS
FOR BASIC OPERATIONS USE THE SAME NAME AND INCLUDE ADD,SUBSTRACT,MUNTIPLY,DIVIDE,REMAINDER,AND POWER
ARTHEMATIC OPERATORS +,*,/ AND 